### ISSUE TITLE
Andrew P. Task List - 2023/2/17 ~ 2023/2/24 for Release 3

### ISSUE THREAD

**Issue by ReviveZygarde** [MangoDragonHub/BasketBallProject#25]
- [x] Implement additional Animations created by Brian
- [x] Implement Sound (at least add placeholders until given the finished sound files)
- [x] Add dribbling ball once the ball has been obtained by the player
