### ISSUE TITLE
andrewp 2023/3/12 - 3/17 task list

### ISSUE THREAD

**Issue by ReviveZygarde** [MangoDragonHub/BasketBallProject#31]
- [x] Look into how I can make a floating translucent “vision line” that represents the arch/distance between the player and the basketball hoop.
- [x] Change the player input so that you shoot the ball as you release the button instead of a normal push. As you keep the button held down, the “vision line” appears
- [x] Change the logic behind the basketBallHandler so it can accommodate 2 players.
- [x] Implement a second player

**Comment by ReviveZygarde** [comment]
scrap the vision line related tasks
