### ISSUE TITLE
andrewp - MULTIPLAYER TASK LIST 2023/3/17 ~ 2023/3/24

### ISSUE THREAD

**Issue by ReviveZygarde** [MangoDragonHub/BasketBallProject#35]
- [x] Fix MANY BUGS as possible with the ball in 2 player gameplay:
    ⁃    Let the game only allow 1 player do the dribble animation so it prevents the ball from teleporting
    ⁃    Create an invisible wall around the player with the ball if the opponent is NOT doing a Steal/offensive. Disable the invisible wall once opponent does the offense.
- [x] Implement animations for the offense/defense and program when the "invisible" barrier disappears
- [x] Give particles to the Basketball and when to enable/disable it
