### ISSUE TITLE
AndrewP task list 2023/4/7 ~ 4/14

### ISSUE THREAD

**Issue by ReviveZygarde** [MangoDragonHub/BasketBallProject#42]
- [x] Fix the Origin coordinate bug with the ball when the player shoots. Inside FindRightHand.
- [x] Implement steal attack and what happens on both players’ ends.
- [x] Make sure the new player prefabs use TestGuy2Anim not the old one.
- [x] Add code to IgnoreCollisionWithBall in PSM script.
- [x] Player automatically turning towards the basketball hoop when shooting, before the shooting anim starts.

**Comment by ReviveZygarde** [comment]
For the task [Fix the Origin coordinate bug with the ball when the player shoots], I added a state machine to the ballHandler.

**Comment by ReviveZygarde** [comment]
I changed multiple boolean variables I originally added and turned them into 1 consolidated state machine.
