### ISSUE TITLE
andrewp task list 2023/4/15 - 4/21

### ISSUE THREAD

**Issue by ReviveZygarde** [MangoDragonHub/BasketBallProject#50]
- [x] Implement slam dunk move
- [ ] make the character controller move automatically when performing it
- [x] implement "special shot meter" ?
- [x] implement bonus offense move

**Comment by ReviveZygarde** [comment]
scrapped [make the character controller move automatically when performing it], found an alternative way of doing this.
