### ISSUE TITLE
Milestone 1 task ideas

### ISSUE THREAD

**Issue by dantogno** [MangoDragonHub/BasketBallProject#6]
1. [x] Set up scene with court / basket goals, invisible collision around court to keep ball inbounds, stationary main camera that shows the whole court, and playable character that controls correctly
2. [x] Create a ball with a physics material on it that bounces how you think is fun and with appropriate friction
7. [x] Create an animation controller for the player character so that when it moves it plays an animation and faces the right direction.
3. [x] If the player touches the ball, he should pick it up (set the rigidbody on the ball to isKinematic and attach the ball to the player)
4. [x] Pressing a button should placeholder shoot the ball toward where the player is facing (detach the ball, set isKinematic to false, add some impulse force to the ball toward the direction the player is facing (player.transform.forward * shotStrength)
5. [x] Come up with logic to determine a shot scoring percentage. It should involve distance from the basket and the player character's shooting stat. Create a diagram that explains it that you can use to show David or others for your portfolio and then work on programming it after that. There should be a function like `GetShotPercentage` that returns a number between 0 and 1 based on these two factors (are there more factors in shot success Moving maybe?). A 1 would be 100% chance of scoring, a 0 is 0%.
6. [x] Make a function for determining if a shot scores like `CheckIfShotScores`. It should use `GetShotPercentage` to get a number between 0 and 1 and then return true or false based on the percentage. So if a shot percentage is .8 there should be an 80% chance of `CheckIfShotScores` returning true.
8. [ ] Create a player prefab with a script that has a PlayerIndex variable. This index should determine what gamepad / controller controls the character. Add two instances of the player prefab to the scene so that you have a player 1 and player 2 that move around w/ correct gamepads

**Comment by MangoDragonHub** [comment]
The Boundaries are set up and the ball physics are set. Currently now, I'm making the Animation Controller to work with a demo mesh

**Comment by MangoDragonHub** [comment]
Currently working on the Animation System and making the animation correlate with the movement system.

**Comment by MangoDragonHub** [comment]
Basic Idle and Running in the animation system works. The shooting animation is in the system but I'm trying to figure out how to connect basic actions to the controller.

**Comment by MangoDragonHub** [comment]
The Basic Animation System is complete with the core animation works, now I need to get the player to shoot on command.

**Comment by MangoDragonHub** [comment]
We're pushing the rest of these tasks for Milestone 2.

**Comment by MangoDragonHub** [comment]
Score Counter has been readded and is functional.

**Comment by MangoDragonHub** [comment]
Closing issue, we found some way to get two players to work. It's a bit janky but it works for the most part.
