### ISSUE TITLE
andrewp FINAL TASK LIST

### ISSUE THREAD

**Issue by ReviveZygarde** [MangoDragonHub/BasketBallProject#60]
- [x] Playtest, fix bugs
- [x] Make the slam dunk area appropriate for each player instead of doing the slam dunk but just throwing the ball across the whole court
- [x] Add secret easter egg?
